site_name: GitHub User Guide
docs_dir: docs

theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - toc.integrate
    - content.code.copy
  palette:
    # Light mode
    - scheme: default
      primary: magenta
      accent: magenta
      toggle:
        icon: material/weather-night
        name: Dark mode

    # Dark mode
    - scheme: slate
      primary: magenta
      accent: magenta
      toggle:
        icon: material/weather-sunny
        name: Light mode

nav:
  - Home: index.md
  - Gitbash terminal connection: gitbash-vscode-terminal-connection.md
  - New GitHub repository: new-github-repo.md
  - Pushing existing project: pushing-existing-project.md
  - Working with existing code on GitHub: working-with-existing-code-on-github.md
  - Glossary: glossary.md
  - Troubleshooting: troubleshooting.md
  


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - attr_list