site_name: GitHub User Guide 
docs_dir: docs

theme:
 name: material

nav:
  - Home: 
    - Intended Users: home.md#intended users 
    - Prerequisite Knowledge: home.md#prerequisite knowledge 
    - Software Requirements: home.md#software requirements 
    - Procedures Overview: home.md#procedures overview 
    - Typographical Conventions: home.md#typographical conventions 
    - Notes and warning Messages: home.md#notes and warning messages 

    # Dark mode
    - scheme: slate
      primary: magenta
      accent: magenta
      toggle:
        icon: material/weather-sunny
        name: Light mode

nav:
  - Home: home.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences